# Basic
title: Zhao Zhao
subtitle: 
welcome_message: <a href="https://www.linkedin.com/in/zhao-zhao/" target="_blank">LinkedIn</a>
description: Personal Website
creator: <a href="http://zhaozhao.name">@zhaozhao</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://zhaozhao.name'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    linkedin: zhaozhao
    github: noelzhao
    mail: jackzhao2017@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
